version: '3.7'
services:
  postgres-sweepstakes:
    container_name: postgres-sweepstakes
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sweepstakes
  sweepstakes:
    container_name: sweepstakes
    image: sweepstakes
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sweepstakes:5432/sweepstakes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSOWRD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-sweepstakes